# Generated by Django 3.1.1 on 2020-11-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201111_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video%y')),
            ],
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='username',
        ),
    ]
