# Generated by Django 3.1.1 on 2020-11-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201125_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('crs_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
